<a href="https://colab.research.google.com/github/claudio-jin/Checkpoint-Python-ML/blob/main/Checkpoint_Dirsuptive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Checkpoint de disruptive</h1>




In [ ]:
#importando bibliotecas

import pandas as pd
import numpy as np

In [ ]:
#1ª célula
df = pd.read_table("/home/breast-cancer.data", delimiter = ",") #lendo o arquivo .data "breast cancer"
df.columns = ['target', 'age', 'menopause','tumor-size', 'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad', 'irradiant'] #nomeando as colunas

In [ ]:
#2ªcélula
df.replace('?', np.nan, inplace = True) #transformando campos com o valor de "?" em NaN
df

target    age menopause tumor-size inv-nodes node-caps  \
0    no-recurrence-events  40-49   premeno      20-24       0-2        no   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  60-69      ge40      15-19       0-2        no   
3    no-recurrence-events  40-49   premeno        0-4       0-2        no   
4    no-recurrence-events  60-69      ge40      15-19       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
280     recurrence-events  30-39   premeno      30-34       0-2        no   
281     recurrence-events  30-39   premeno      20-24       0-2        no   
282     recurrence-events  60-69      ge40      20-24       0-2        no   
283     recurrence-events  40-49      ge40      30-34       3-5        no   
284     recurrence-events  50-59      ge40      30-34       3-5        no   

     deg-malig breast breast-quad irradiant  
0            2  right    right_up        no  
1            2   left    left_low        no  
2            2  right     left_up        no  
3            2  right   right_low        no  
4            2   left    left_low        no  
..         ...    ...         ...       ...  
280          2   left     left_up        no  
281          3   left     left_up       yes  
282          1  right     left_up        no  
283          3   left    left_low        no  
284          3   left    left_low        no  

[285 rows x 10 columns]

In [ ]:
#df.loc[pd.isna(df['node-caps']), 'node-caps'].shape[0] #verifica quantidade de "NaN" na coluna 'node-caps'

In [ ]:
#3ª célula
df.isna().sum() #soma quantidade de 'NaN' no dataframe

target         0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiant      0
dtype: int64

In [ ]:
#4ª célula
#função para calcular porcentagem de NaN em coluna especificada
def calc_percentual_indefinido(dataframe, coluna):
  indefinidos = dataframe.loc[pd.isna(dataframe[coluna]), coluna].shape[0]
  total = dataframe[coluna].shape[0]

  return (indefinidos/total) * 100

In [ ]:
calc_percentual_indefinido(df, 'node-caps') #teste de função

2.807017543859649

In [ ]:
calc_percentual_indefinido(df, 'breast-quad') #teste de função

0.3508771929824561

In [ ]:
data = df.dropna()  #novo data frame recebendo o dataframe 'df' sem as linhas que contém "NaN"

In [ ]:
calc_percentual_indefinido(data, 'node-caps') #teste de função, verifica porcentagem de 'NaN'

0.0

In [ ]:
calc_percentual_indefinido(data, 'breast-quad') #teste de função, verifica porcentagem de 'NaN'

0.0

In [ ]:
#5ª célula
#função one hot
def one_hot(categorias, valor):
  categorias = list(set(categorias))
  indice = categorias.index(valor)
  vetor = np.zeros(len(categorias))
  vetor[indice] = 1
  return vetor

In [ ]:
#data['node-caps']

In [ ]:
one_hot(data['node-caps'], 'no')  #teste de função

array([0., 1.])

In [ ]:
one_hot(data['tumor-size'], '25-29')  #teste de função

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
data['tumor-size'].unique() #valores que se repetem na coluna tumor-size

array(['20-24', '15-19', '0-4', '25-29', '50-54', '10-14', '30-34',
       '40-44', '35-39', '5-9', '45-49'], dtype=object)

In [ ]:
data['target'].unique()

array(['no-recurrence-events', 'recurrence-events'], dtype=object)

In [ ]:
#6ª célula

data['age'] = [ one_hot(data['age'], _) for _ in data['age'] ]
data['menopause'] = [ one_hot(data['menopause'], _) for _ in data['menopause'] ]
data['tumor-size'] = [ one_hot(data['tumor-size'], _) for _ in data['tumor-size'] ]
data['inv-nodes'] = [ one_hot(data['inv-nodes'], _) for _ in data['inv-nodes'] ]
data['node-caps'] = [ one_hot(data['node-caps'], _) for _ in data['node-caps'] ]
data['deg-malig'] = [ one_hot(data['deg-malig'], _) for _ in data['deg-malig'] ]
data['breast'] = [ one_hot(data['breast'], _) for _ in data['breast'] ]
data['breast-quad'] = [ one_hot(data['breast-quad'], _) for _ in data['breast-quad'] ]
data['irradiant'] = [ one_hot(data['irradiant'], _) for _ in data['irradiant'] ]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row

In [ ]:
data['tumor-size'] [0]  #teste de função

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
data['target'] = [ one_hot(data['target'], _) for _ in data['target'] ] #aplicando one hot na coluna target

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
#7ª célula
labels = data['target'].values  #labels recebe valores da coluna 'target'

In [ ]:
labels

array([array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), a

In [ ]:
#8ª célula
data = data.drop(['target'], axis = 1)  #removendo coluna do 'target'
data.head(10)

age        menopause  \
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   
2  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   
4  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0, 0.0]   
6  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
7  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   
8  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0]   

                                          tumor-size  \
0  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
4  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   
6  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
7  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
8  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
9  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   

                             inv-nodes   node-caps        deg-malig  \
0  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
1  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
3  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
5  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
6  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [1.0, 0.0, 0.0]   
7  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
8  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 1.0, 0.0]   
9  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  [0.0, 0.0, 1.0]   

       breast                breast-quad   irradiant  
0  [0.0, 1.0]  [0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 1.0]  
1  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
2  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 1.0]  
3  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 1.0]  
4  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
5  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
6  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
7  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
8  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 1.0]  
9  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]

In [ ]:
#Função para transformar valores em uma lista
def vetorizar(age, menopause, tumorSize, invNodes, nodeCaps, degMalig, breast, breastQuad, irradiant):
  return age.tolist() + menopause.tolist() + tumorSize.tolist() + invNodes.tolist() + \
        nodeCaps.tolist() + degMalig.tolist() + breast.tolist() + breastQuad.tolist() + irradiant.tolist()

In [ ]:
entrada = [vetorizar(*_) for _ in data.values]

In [ ]:
#salvar os dados para usar depois
np.savetxt("/home/input_fit.csv", entrada, delimiter = ',')
np.savetxt("/home/labels_target.csv", labels.tolist(), delimiter = ',')

In [ ]:
#Com os dados tratados, vamos mandar pra classificação
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [ ]:
#Recebendo os df
input_data = np.loadtxt("/home/input_fit.csv", delimiter = ',')
target_data = np.loadtxt("/home/labels_target.csv", delimiter = ',')

In [ ]:
input_data_train, input_data_test, target_data_train, target_data_test = train_test_split(input_data, target_data, train_size = 0.7, random_state=42) #, stratify = target_data

In [ ]:
target_data_test.shape  #conferindo quantidade de linhas

(83, 2)

In [ ]:
target_data_train

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [ ]:
input_data_train[:20]  #conferindo quantidade de linhas

array([[0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,

In [ ]:
input_data_test[82]

array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0.])

In [ ]:
redeneural = MLPClassifier(verbose= False, #retorna mensagem na tela
                           max_iter=30000,  #número de épocas
                           tol=0.00000001,  #tolerância para otimização
                           activation = 'logistic', #activation = 'logistic'  Função de ativação
                          #  solver = 'lbfgs',
                           hidden_layer_sizes=(8,8,8),  #3 camadas ocultas com 8 neuronios(n.neuronio < 2*n.entradas)
                           learning_rate_init=0.00001,
                           learning_rate = 'adaptive').fit(input_data_train, target_data_train) #taxa de aprendizado adaptativo, muda conforme a tolerancia é atingida em duas epocas/
                           #mandando dados para treinar a rede neural

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (30000) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
redeneural.score(input_data_test,target_data_test)

0.7108433734939759

In [ ]:
a = redeneural.predict(input_data_test)

In [ ]:
#Dataset após o train test split
df_target_train = pd.DataFrame(target_data_train)
df_target_test = pd.DataFrame(target_data_test)

df_target_train.columns = ['no-recurrents', 'recurrents']
df_target_test.columns = ['no-recurrents', 'recurrents']

In [ ]:
df_target_train.append(df_target_test)

no-recurrents  recurrents
0             1.0         0.0
1             0.0         1.0
2             1.0         0.0
3             1.0         0.0
4             1.0         0.0
..            ...         ...
78            1.0         0.0
79            1.0         0.0
80            1.0         0.0
81            1.0         0.0
82            0.0         1.0

[276 rows x 2 columns]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(target_data_test, a))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        59
           1       0.00      0.00      0.00        24

   micro avg       0.71      0.71      0.71        83
   macro avg       0.36      0.50      0.42        83
weighted avg       0.51      0.71      0.59        83
 samples avg       0.71      0.71      0.71        83



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
